db:
  path_to_vaults: /Users/amihaio/Documents/personal/FinDash/dbs/
  trans_db_path: trans_db
  cat_db_path: cat_db/cat_db.pq
  payee2cat_db_path: cat_db/payee2cat_db.json
  cat2payee_db_path: cat_db/cat2payee_db.json
  auto_cat_db_path: auto_cat_db.pq
  accounts:  accounts.yaml

user:
  vault_name: dev

