name: Lint with flake8
run-name: Lint with flake8
on:
  pull_request:
    paths:
      - '*.py'

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: x64
      - name: Checkout code
        uses: actions/checkout@v3
      - name: install poetry and dependencies
        run: |
          pip install poetry
          poetry -install
      - name: Run flake8
        run: |
          flake8 
